- name: frontend configuration
  hosts: frontend
  become: yes

  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove html dir
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent
  
  - name: remove html dir
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: present

  - name: download the frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: extract the frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes


      

