- name: configure mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_password: "ExpenseApp@1"
    login_host: "mysql.vensa.online"

  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: 
      - mysql-server
      state: present

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true

  # - name: install PyMySQL to ansible
  #   ansible.builtin.package:
  #     name:
  #     - pyMySQL
  #     executable: pip3.9
